version: "3"

volumes:
  data:

services:
  db:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGODB DATABASE: book-store
  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379